# Generated by Django 3.2.7 on 2022-10-29 14:02

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(default=app.models.random_string_generator, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos')),
                ('description', models.TextField(blank=True, null=True)),
                ('published', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(blank=True, null=True, related_name='video_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.CharField(default=app.models.random_channelid_generator, max_length=100, primary_key=True, serialize=False)),
                ('channelname', models.CharField(blank=True, max_length=255, null=True)),
                ('channelimg', models.ImageField(blank=True, null=True, upload_to='channeluser_img')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banner')),
                ('channeluser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channeluser', to=settings.AUTH_USER_MODEL)),
                ('subscribers', models.ManyToManyField(blank=True, null=True, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
