# Generated by Django 3.2.7 on 2022-10-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_history_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='post',
        ),
        migrations.AddField(
            model_name='history',
            name='vid',
            field=models.ManyToManyField(related_name='vid', to='app.Video'),
        ),
    ]
