# Generated by Django 3.2.7 on 2022-10-31 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20221031_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.video'),
        ),
    ]
