# Generated by Django 3.2.7 on 2022-11-01 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_alter_history_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='liked',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
