# Generated by Django 3.2.7 on 2022-11-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_notification_is_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_body',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
    ]
