# Generated by Django 3.2.7 on 2022-11-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_comment_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvideo',
            name='watched',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='watched',
            field=models.IntegerField(default=0),
        ),
    ]
