# Generated by Django 3.2.7 on 2022-11-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20221103_1205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalVideo',
        ),
    ]
