# Generated by Django 3.2.7 on 2022-11-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_delete_historicalvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channeldescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
