# Generated by Django 3.2.7 on 2022-11-03 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0025_channel_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='watchlater',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlater', to=settings.AUTH_USER_MODEL),
        ),
    ]
