# Generated by Django 3.2.7 on 2022-11-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='visibility',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=100),
        ),
    ]
