# Generated by Django 3.2.7 on 2022-11-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_video_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(blank=True, max_length=99999, primary_key=True, serialize=False, unique=True),
        ),
    ]
