# Generated by Django 3.2.7 on 2022-11-05 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20221105_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commented_on',
        ),
        migrations.AddField(
            model_name='something',
            name='comment_body',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='something',
            name='comment_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.video'),
        ),
        migrations.AddField(
            model_name='something',
            name='commented_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
