# Generated by Django 3.2.7 on 2022-11-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20221105_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='something',
            name='comment_body',
            field=models.CharField(max_length=9999, null=True),
        ),
    ]
