# Generated by Django 3.2.7 on 2022-11-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_something_comment_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
