# Generated by Django 3.2.7 on 2022-11-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_delete_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
