# Generated by Django 3.2.7 on 2022-11-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_delete_feature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
