# Generated by Django 3.2.7 on 2022-11-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_videos',
            field=models.ManyToManyField(related_name='playlist_vidoes', to='app.Video'),
        ),
    ]
