# Generated by Django 3.2.7 on 2022-11-08 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20221108_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='something',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.something'),
        ),
    ]
