# Generated by Django 3.2.7 on 2022-11-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_something_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='published',
        ),
    ]
