# Generated by Django 3.2.7 on 2022-11-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_remove_video_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
