# Generated by Django 3.2.7 on 2022-11-24 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_video_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_created',
        ),
    ]
