# Generated by Django 3.2.7 on 2022-11-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_remove_playlist_playlist_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
