# Generated by Django 4.1.7 on 2023-08-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_remove_video_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channelslug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
