# Generated by Django 4.1.7 on 2023-08-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_rename_video_video_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_file',
            new_name='video',
        ),
    ]
