# Generated by Django 4.1.7 on 2023-08-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_alter_shorts_short_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='something',
            name='comment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
