# Generated by Django 4.1.7 on 2023-08-23 10:40

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_alter_something_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='something',
            name='comment_id',
            field=models.CharField(blank=True, default=app.models.random_commentid_generator, max_length=255, null=True),
        ),
    ]
